name: pages-github-deployment

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # Automatically resolves the latest Node.js 16 version
          cache: "yarn" # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          VITE_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}

      - name: Deploy
        run: |
          git config --global user.name "Jared"
          git config --global user.email "${{ secrets.EMAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          yarn deploy
        env:
          CI: false # Ensures proper behavior in CI environments
